name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.10.0
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.1.2
  video_player: ^2.9.3
  wakelock_plus: ^1.2.8

dependency_overrides:
  video_player:
    git:
      url: git@github.com:http600/packages.git
      path: packages/video_player/video_player
      ref: work

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
